name: GDevelop Issues automatic workflow
on: [issues]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues about adding a new example without providing anything
      uses: arkon/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        type: "body"
        regex: ".*INSERT the link to your game here, or add it as an attachment.*"
        message: "Hi @${issue.user.login}! ðŸ‘‹ This issue was automatically closed because it seems that you have not included any example.\n\nGitHub is a place for the technical development of GDevelop itself - you may want to go on the [forum](https://forum.gdevelop-app.com/), the Discord chat or [read the documentation](http://wiki.compilgames.net/doku.php/gdevelop5/start) to learn more about GDevelop. Thanks!"
    - name: Autoclose issues about adding a bug without changing the bug report template
      uses: arkon/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        type: "body"
        regex: ".*Scroll down to '\\.\\.\\.\\.'.*"
        message: "Hi @${issue.user.login}! ðŸ‘‹ This issue was automatically closed because it seems that you have not included any steps to reproduce the bug.\n\nGitHub is a place for the technical development of GDevelop itself - you may want to go on the [forum](https://forum.gdevelop-app.com/), the Discord chat or [read the documentation](http://wiki.compilgames.net/doku.php/gdevelop5/start) to learn more about GDevelop. Thanks!"
    - name: Autoclose known beta 105 web-app update bug
      uses: arkon/issue-closer-action@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        type: "body"
        regex: ".*_instance.getRawFloatProperty is not a function.*"
        message: "Hi @${issue.user.login}! ðŸ‘‹ This issue was automatically closed as this seems to be a known bug. It can be solved by **closing entirely the web-app and opening it again**. This will allow the web-app to auto-update and the problem should be gone."
